### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by Sacristan** [artursbraucs/banklink#1]
➜  banklink git:(master) rake
/Users/sac/.rvm/rubies/ruby-2.0.0-p451/bin/ruby -I"lib:lib:test" -I"/Users/sac/.rvm/gems/ruby-2.0.0-p451/gems/rake-10.1.1/lib" "/Users/sac/.rvm/gems/ruby-2.0.0-p451/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/*_/__test.rb" 
Run options: 
# Running tests:

[ 4/12] BanklinkNotificationTest#test_accessors = 0.00 s  
  1) Error:
BanklinkNotificationTest#test_accessors:
NoMethodError: undefined method `civil' for Date:Class
    /Users/sac/banklink/lib/banklink/swedbank/notification.rb:102:in`received_at'
/Users/sac/banklink/test/banklink_notification_test.rb:24:in `test_accessors'

Finished tests in 0.034493s, 347.8967 tests/s, 579.8278 assertions/s.  
12 tests, 20 assertions, 0 failures, 1 errors, 0 skips

ruby -v: ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin13.0.0]
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" -I"/Users/sac/.rvm/gems/ruby-2.0.0-p451/gems/rake-10.1.1/lib" "/Users/sac/.rvm/gems/ruby-2.0.0-p451/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/*_/__test.rb" ]
/Users/sac/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
/Users/sac/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)

![screenshot 2014-05-29 12 28 41 2](https://cloud.githubusercontent.com/assets/3949694/3116103/d81b0ec8-e713-11e3-8d96-cc1080551459.png)

**Comment by artursbraucs** [comment]
Fixed tests for 2.0.0 Ruby.
