### ISSUE TITLE
Stack level too deep GETTER ->  Banklink::Swedbank.service_url 

### ISSUE THREAD

**Issue by Sacristan** [artursbraucs/banklink#2]
Loading development environment (Rails 4.0.0)
SETTING
 :001 > Banklink::Swedbank.service_url = "/tram/tram/ta/ram/"
 => "/tram/tram/ta/ram/"
GETTING
 :002 > Banklink::Swedbank.service_url
SystemStackError: stack level too deep
    from /Users/sac/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/irb/workspace.rb:86
Maybe IRB bug!

Same story when running server

**Comment by artursbraucs** [comment]
This should work now! Fixed getter.
